# Importar la librería

In [1]:
import numpy as np

In [2]:
from numpy import random

# Arreglos de Numpy

In [3]:
l1 = list(range(10))
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
type(l1)

list

In [5]:
arr_np1 = np.array(l1,dtype=np.int8)
arr_np1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [6]:
type(arr_np1)

numpy.ndarray

In [7]:
lmd1 = [[1,2,3],[4,5,6]]
lmd1

[[1, 2, 3], [4, 5, 6]]

In [8]:
arr_md_np1 = np.array(lmd1)
arr_md_np1

array([[1, 2, 3],
       [4, 5, 6]])

Para ver el tipo de dato de los elementos del arreglo

In [9]:
arr_md_np1.dtype

dtype('int64')

Para crear arreglos sin necesidad de listas

In [10]:
anp1 = np.arange(1,10)
anp1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
anp1.dtype

dtype('int64')

In [12]:
anp2 = np.arange(2,15,3,dtype=np.float32)
anp2

array([ 2.,  5.,  8., 11., 14.], dtype=float32)

In [13]:
anp2.dtype

dtype('float32')

Para crear un arreglo de 5 elementos entre 0 y 4 a pasos iguales

In [14]:
lnp1 = np.linspace(0,4,5)
lnp1

array([0., 1., 2., 3., 4.])

In [15]:
lnp1.dtype

dtype('float64')

Un arreglo de 3 elementos entre 0 y 4 a pasos iguales

In [16]:
lnp2 = np.linspace(0,4,3,dtype=np.float32)
lnp2

array([0., 2., 4.], dtype=float32)

In [17]:
lnp2.dtype

dtype('float32')

Un arreglo de 10 elementos entre 0 y 5 a pasos iguales

In [18]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

Un arreglo de ceros

In [19]:
c0 = np.zeros(10)

In [20]:
type(c0)

numpy.ndarray

In [21]:
c0.dtype

dtype('float64')

In [22]:
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
np.zeros((10,1),dtype=np.int8)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=int8)

In [24]:
np.zeros((5,2),dtype=np.int16)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int16)

In [25]:
np.zeros((3,4),dtype=np.float32)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

Un arreglo de unos

In [26]:
u0 = np.ones(10)
u0

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Para saber el tamaño

In [27]:
u0.size

10

Otros ejemplos, con otras dimensiones y otros tipo de dato

In [28]:
np.ones((1,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
np.ones((4,3),dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

Para crear un arreglo de tamaño 5, cuyos elementos son números aleatorios entre 0 y 3

In [31]:
rnpa1 = np.random.randint(0,4,5)
rnpa1

array([2, 3, 0, 1, 0])

In [32]:
rnpa1.dtype

dtype('int64')

In [33]:
rnpa1.size

5

Para que el arreglo sea multidimensional

In [34]:
rnpa2 = np.random.randint(0,4,(4,3))
rnpa2

array([[0, 3, 3],
       [3, 3, 1],
       [0, 1, 1],
       [3, 1, 1]])

In [35]:
rnpa2.size

12

In [36]:
rnpa2.shape

(4, 3)

# Indexado

In [37]:
randarr = np.random.randint(0,4,(4,6))
randarr

array([[1, 1, 0, 3, 1, 1],
       [0, 1, 1, 3, 1, 0],
       [2, 3, 3, 0, 0, 3],
       [2, 1, 0, 0, 0, 1]])

Primera fila

In [38]:
randarr[0]

array([1, 1, 0, 3, 1, 1])

También para la primera fila

In [39]:
randarr[0:1]

array([[1, 1, 0, 3, 1, 1]])

Para la primera y segunda fila

In [40]:
randarr[0:2]

array([[1, 1, 0, 3, 1, 1],
       [0, 1, 1, 3, 1, 0]])

Para coger la tercera columna

In [41]:
randarr[:,2]

array([0, 1, 3, 0])

Para coger la tercera y cuarta columna

In [42]:
randarr[:,2:4]

array([[0, 3],
       [1, 3],
       [3, 0],
       [0, 0]])

Para la primera y segunda fila, la primera columna

In [43]:
randarr[0:2,0]

array([1, 0])

Para la primera y segunda fila, desde la primera hasta la tercera columna

In [44]:
randarr[0:2,0:4]

array([[1, 1, 0, 3],
       [0, 1, 1, 3]])

Para el elemento de la fila 3 y columna 4

In [45]:
randarr[3,4]

0

También puede hacer

In [46]:
randarr.item(3,4)

0

In [47]:
randarr.item(22)

0

Para coger ciertos elementos

In [48]:
np.take(randarr,[1,15,20])

array([1, 0, 0])

In [49]:
randarr

array([[1, 1, 0, 3, 1, 1],
       [0, 1, 1, 3, 1, 0],
       [2, 3, 3, 0, 0, 3],
       [2, 1, 0, 0, 0, 1]])

Para reemplazar elementos

In [50]:
np.put(randarr,[1,15,20],[8,8,8])
randarr

array([[1, 8, 0, 3, 1, 1],
       [0, 1, 1, 3, 1, 0],
       [2, 3, 3, 8, 0, 3],
       [2, 1, 8, 0, 0, 1]])

Para invertir el orden de las filas

In [51]:
randarr[::-1]

array([[2, 1, 8, 0, 0, 1],
       [2, 3, 3, 8, 0, 3],
       [0, 1, 1, 3, 1, 0],
       [1, 8, 0, 3, 1, 1]])

Para extraer los elementos pares

In [52]:
randarr[randarr % 2 == 0]

array([8, 0, 0, 0, 2, 8, 0, 2, 8, 0, 0])

Para extraer los elementos mayores que 2

In [53]:
randarr[randarr > 2]

array([8, 3, 3, 3, 3, 8, 3, 8])

Mayores que 1 e impares

In [54]:
randarr[(randarr > 1) & (randarr % 2 == 1)]

array([3, 3, 3, 3, 3])

# Remodelar arreglos

In [55]:
randarr = np.random.randint(0,4,(4,7))
randarr

array([[3, 0, 3, 0, 0, 3, 1],
       [1, 3, 3, 3, 1, 3, 1],
       [2, 2, 2, 3, 2, 1, 1],
       [2, 3, 3, 3, 2, 3, 1]])

In [56]:
randarr.reshape((1,28))

array([[3, 0, 3, 0, 0, 3, 1, 1, 3, 3, 3, 1, 3, 1, 2, 2, 2, 3, 2, 1, 1, 2,
        3, 3, 3, 2, 3, 1]])

In [57]:
randarr.reshape((2,14))

array([[3, 0, 3, 0, 0, 3, 1, 1, 3, 3, 3, 1, 3, 1],
       [2, 2, 2, 3, 2, 1, 1, 2, 3, 3, 3, 2, 3, 1]])

In [58]:
randarr.reshape((28,1))

array([[3],
       [0],
       [3],
       [0],
       [0],
       [3],
       [1],
       [1],
       [3],
       [3],
       [3],
       [1],
       [3],
       [1],
       [2],
       [2],
       [2],
       [3],
       [2],
       [1],
       [1],
       [2],
       [3],
       [3],
       [3],
       [2],
       [3],
       [1]])

In [59]:
randarr.reshape((14,2))

array([[3, 0],
       [3, 0],
       [0, 3],
       [1, 1],
       [3, 3],
       [3, 1],
       [3, 1],
       [2, 2],
       [2, 3],
       [2, 1],
       [1, 2],
       [3, 3],
       [3, 2],
       [3, 1]])

La forma transpuesta

In [60]:
randarr.transpose()

array([[3, 1, 2, 2],
       [0, 3, 2, 3],
       [3, 3, 2, 3],
       [0, 3, 3, 3],
       [0, 1, 2, 2],
       [3, 3, 1, 3],
       [1, 1, 1, 1]])

In [61]:
randarr

array([[3, 0, 3, 0, 0, 3, 1],
       [1, 3, 3, 3, 1, 3, 1],
       [2, 2, 2, 3, 2, 1, 1],
       [2, 3, 3, 3, 2, 3, 1]])

Cuidado con cambiar el tamaño. No es intuitivo

In [62]:
np.resize(randarr,(4,6))

array([[3, 0, 3, 0, 0, 3],
       [1, 1, 3, 3, 3, 1],
       [3, 1, 2, 2, 2, 3],
       [2, 1, 1, 2, 3, 3]])

In [63]:
np.resize(randarr,(4,8))

array([[3, 0, 3, 0, 0, 3, 1, 1],
       [3, 3, 3, 1, 3, 1, 2, 2],
       [2, 3, 2, 1, 1, 2, 3, 3],
       [3, 2, 3, 1, 3, 0, 3, 0]])

Para aplanar el arreglo

In [64]:
randarr.flatten()

array([3, 0, 3, 0, 0, 3, 1, 1, 3, 3, 3, 1, 3, 1, 2, 2, 2, 3, 2, 1, 1, 2,
       3, 3, 3, 2, 3, 1])

Operaciones que modifican el arreglo "in place". No generan un arreglo nuevo, modifica el arreglo ya existente.

In [65]:
randarr

array([[3, 0, 3, 0, 0, 3, 1],
       [1, 3, 3, 3, 1, 3, 1],
       [2, 2, 2, 3, 2, 1, 1],
       [2, 3, 3, 3, 2, 3, 1]])

In [66]:
randarr.sort(axis=0)
randarr

array([[1, 0, 2, 0, 0, 1, 1],
       [2, 2, 3, 3, 1, 3, 1],
       [2, 3, 3, 3, 2, 3, 1],
       [3, 3, 3, 3, 2, 3, 1]])

In [67]:
randarr.sort(axis=1)
randarr

array([[0, 0, 0, 1, 1, 1, 2],
       [1, 1, 2, 2, 3, 3, 3],
       [1, 2, 2, 3, 3, 3, 3],
       [1, 2, 3, 3, 3, 3, 3]])

# Concatenar arreglos

In [68]:
randarr1 = np.random.randint(1,10,(3,3))
randarr1

array([[5, 7, 5],
       [2, 8, 5],
       [5, 6, 3]])

In [69]:
randarr2 = np.random.randint(1,10,(3,3))
randarr2

array([[2, 9, 1],
       [2, 2, 2],
       [8, 8, 2]])

Para concatenar arreglos de forma vertical

In [70]:
np.vstack((randarr1,randarr2))

array([[5, 7, 5],
       [2, 8, 5],
       [5, 6, 3],
       [2, 9, 1],
       [2, 2, 2],
       [8, 8, 2]])

Para concatenar arreglos de forma horizontal

In [71]:
np.hstack((randarr1,randarr2))

array([[5, 7, 5, 2, 9, 1],
       [2, 8, 5, 2, 2, 2],
       [5, 6, 3, 8, 8, 2]])

# Partir arreglos

In [72]:
randarr = np.random.randint(1,6,(3,6))
randarr

array([[3, 4, 5, 1, 5, 2],
       [2, 1, 2, 3, 5, 5],
       [3, 5, 4, 3, 3, 5]])

Para dividir el arreglo a lo largo del eje horizontal

In [73]:
np.hsplit(randarr, 2)

[array([[3, 4, 5],
        [2, 1, 2],
        [3, 5, 4]]),
 array([[1, 5, 2],
        [3, 5, 5],
        [3, 3, 5]])]

In [74]:
np.hsplit(randarr, 3)

[array([[3, 4],
        [2, 1],
        [3, 5]]),
 array([[5, 1],
        [2, 3],
        [4, 3]]),
 array([[5, 2],
        [5, 5],
        [3, 5]])]

In [75]:
np.hsplit(randarr, 6)

[array([[3],
        [2],
        [3]]),
 array([[4],
        [1],
        [5]]),
 array([[5],
        [2],
        [4]]),
 array([[1],
        [3],
        [3]]),
 array([[5],
        [5],
        [3]]),
 array([[2],
        [5],
        [5]])]

Para dividir el arreglo a lo largo de su eje vertical

In [76]:
np.vsplit(randarr,3)

[array([[3, 4, 5, 1, 5, 2]]),
 array([[2, 1, 2, 3, 5, 5]]),
 array([[3, 5, 4, 3, 3, 5]])]

# Copiar arreglos

Así no se copia un arreglo

In [77]:
randarr1 = np.random.randint(1,6,(3,4))
randarr1

array([[4, 4, 2, 5],
       [2, 1, 4, 3],
       [4, 2, 1, 1]])

In [78]:
randarr2 = randarr1
randarr2

array([[4, 4, 2, 5],
       [2, 1, 4, 3],
       [4, 2, 1, 1]])

In [79]:
randarr2[0,0] = 100

In [80]:
randarr1

array([[100,   4,   2,   5],
       [  2,   1,   4,   3],
       [  4,   2,   1,   1]])

In [81]:
randarr2

array([[100,   4,   2,   5],
       [  2,   1,   4,   3],
       [  4,   2,   1,   1]])

Se observa que randarr1 y randarr2 han sido afectados por la operación, porque randarr2 es simplemente otra referencia que opera sobre el mismo espacio de memoria que randarr1. 

Para copiar se tiene que hacer lo siguiente:

In [82]:
randarr3 = randarr1.copy()
randarr3

array([[100,   4,   2,   5],
       [  2,   1,   4,   3],
       [  4,   2,   1,   1]])

In [83]:
randarr3[0,0] = 1
randarr3

array([[1, 4, 2, 5],
       [2, 1, 4, 3],
       [4, 2, 1, 1]])

In [84]:
randarr2

array([[100,   4,   2,   5],
       [  2,   1,   4,   3],
       [  4,   2,   1,   1]])

In [85]:
randarr1

array([[100,   4,   2,   5],
       [  2,   1,   4,   3],
       [  4,   2,   1,   1]])

De esta forma randarr3 es un arreglo nuevo, con los mismos valores que randarr1.

# Matemática con arreglos

In [86]:
randarr1 = np.random.randint(1,5,3)
randarr1

array([1, 1, 2])

In [87]:
randarr2 = np.random.randint(1,5,3)
randarr2

array([1, 1, 4])

In [88]:
randarr1 + randarr2

array([2, 2, 6])

In [89]:
randarr1 - randarr2

array([ 0,  0, -2])

In [90]:
randarr1 * randarr2

array([1, 1, 8])

In [91]:
randarr1 / randarr2

array([1. , 1. , 0.5])

In [92]:
randarr1 ** randarr2

array([ 1,  1, 16])

In [93]:
randarr1 % randarr2

array([0, 0, 2])

In [94]:
np.exp(randarr1)

array([2.71828183, 2.71828183, 7.3890561 ])

In [95]:
np.log2(randarr1)

array([0., 0., 1.])

In [96]:
np.log10(randarr1)

array([0.     , 0.     , 0.30103])

Operaciones de arreglos con una constante

In [97]:
randarr1 + 10

array([11, 11, 12])

In [98]:
randarr1 * 10

array([10, 10, 20])

In [99]:
randarr1 ** 3

array([1, 1, 8])

In [100]:
randarr1 ** 0.5

array([1.        , 1.        , 1.41421356])

In [101]:
randarr1 % 2 == 0

array([False, False,  True])

In [102]:
randarr1 = randarr1 * (-1)
randarr1

array([-1, -1, -2])

In [103]:
np.absolute(randarr1)

array([1, 1, 2])

# Métodos de arreglos

In [104]:
randarr = np.random.randint(1,10,(3,3))
randarr

array([[8, 6, 2],
       [3, 7, 2],
       [2, 1, 5]])

Sumar de los elementos de las columnas

In [105]:
randarr.sum(axis=0)

array([13, 14,  9])

Suma de los elementos de las filas

In [106]:
randarr.sum(axis=1)

array([16, 12,  8])

Mínimo de cada columna

In [107]:
randarr.min(axis=0)

array([2, 1, 2])

Mínimo de cada fila

In [108]:
randarr.min(axis=1)

array([2, 2, 1])

Máximo de cada columna

In [109]:
randarr.max(axis=0)

array([8, 7, 5])

Máximo de cada fila

In [110]:
randarr.max(axis=1)

array([8, 7, 5])

Los índices de los elementos máximos de cada columna

In [111]:
randarr.argmax(axis=0)

array([0, 1, 2])

Los índices de los elementos máximos de cada fila

In [112]:
randarr.argmax(axis=1)

array([0, 1, 2])

Los índices de los elementos mínimos de de cada columna

In [113]:
randarr.argmin(axis=0)

array([2, 2, 0])

Los índices de los elementos mínimos de cada fila

In [114]:
randarr.argmin(axis=1)

array([2, 2, 1])

# Funciones de comparación

In [115]:
arr1 = np.random.randint(1,10,(3,3))
arr1

array([[2, 7, 9],
       [9, 9, 5],
       [7, 6, 2]])

In [116]:
arr2 = np.random.randint(1,10,(3,3))
arr2

array([[6, 4, 2],
       [7, 9, 8],
       [4, 4, 8]])

In [117]:
np.greater(arr1,arr2)

array([[False,  True,  True],
       [ True, False, False],
       [ True,  True, False]])

In [118]:
np.greater_equal(arr1,arr2)

array([[False,  True,  True],
       [ True,  True, False],
       [ True,  True, False]])

In [119]:
np.less(arr1,arr2)

array([[ True, False, False],
       [False, False,  True],
       [False, False,  True]])

In [120]:
np.less_equal(arr1,arr2)

array([[ True, False, False],
       [False,  True,  True],
       [False, False,  True]])

In [121]:
np.equal(arr1,arr2)

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [122]:
np.not_equal(arr1,arr2)

array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True]])

# Funciones estadísticas

In [123]:
arr = np.random.randint(1,10,(3,3))
arr

array([[1, 9, 8],
       [5, 5, 6],
       [5, 6, 6]])

Promedio aritmético

In [124]:
np.mean(arr)

5.666666666666667

In [126]:
np.average(arr)

5.666666666666667

In [125]:
np.mean(arr,axis=0)

array([3.66666667, 6.66666667, 6.66666667])

In [127]:
np.average(arr,axis=0)

array([3.66666667, 6.66666667, 6.66666667])

In [128]:
np.mean(arr,axis=1)

array([6.        , 5.33333333, 5.66666667])

In [129]:
np.average(arr,axis=1)

array([6.        , 5.33333333, 5.66666667])

Mediana

In [130]:
np.median(arr)

6.0

In [131]:
np.median(arr,axis=0)

array([5., 6., 6.])

In [132]:
np.median(arr,axis=1)

array([8., 5., 6.])

Desviación estándar

In [133]:
np.std(arr)

2.1081851067789197

In [134]:
np.std(arr,axis=0)

array([1.88561808, 1.69967317, 0.94280904])

In [135]:
np.std(arr,axis=1)

array([3.55902608, 0.47140452, 0.47140452])

Varianza

In [136]:
np.var(arr)

4.4444444444444455

In [137]:
np.var(arr,axis=0)

array([3.55555556, 2.88888889, 0.88888889])

In [138]:
np.var(arr,axis=1)

array([12.66666667,  0.22222222,  0.22222222])